### ISSUE TITLE
[Task] 채팅 심화기능 구현

### ISSUE THREAD

**Issue by jsjsjskjs** [codestates/AtoZsports#108]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 채팅방 입.퇴장 여부를 알려주는 기능, 아직 읽지 않은 메세지 확인 기능 구현

### TODO
1. [x] 채팅방 입장 여부 알림
2. [x] 채팅방 퇴장 여부 알림
3. [x] 아직 읽지 않은 메세지 기능

### Estimated time
> Pick one
