### ISSUE TITLE
[Task] 리덕스 초기설정 

### ISSUE THREAD

**Issue by youhavetosleep** [codestates/AtoZsports#38]
### ISSUE
- Group:  `client`
- Type: `bug`, `feature`, `delete`, `sr`
- Detail: fix actions from client redux

### TODO
1. [ ] store 만들고 index.js 연결
2. [ ] action 폴더, 파일 만들기
3. [ ] reducer 폴더, 파일 만들기

### Estimated time
> Pick one
